; normal sprite remaps
incsrc "remaps/ballnchain.asm"
incsrc "remaps/banzai_bill.asm"
incsrc "remaps/big_boo.asm"
incsrc "remaps/blargg.asm"
incsrc "remaps/blurp.asm"
incsrc "remaps/bob_omb.asm"
incsrc "remaps/boo_booblock.asm"
incsrc "remaps/bowling_ball.asm"
incsrc "remaps/bowser_statue.asm"
incsrc "remaps/bullet_bills.asm"
incsrc "remaps/buzzy_beetle.asm"
incsrc "remaps/carrot_top.asm"
incsrc "remaps/castle_block.asm"
incsrc "remaps/chainsaw.asm"
incsrc "remaps/chucks.asm"
incsrc "remaps/chuck_rock.asm"
incsrc "remaps/climbing_koopas.asm"
incsrc "remaps/coingame.asm"                  ; TODO figure out how to handle the coin inheritance
incsrc "remaps/dino.asm"
incsrc "remaps/disco_ball.asm"
incsrc "remaps/dolphins.asm"
incsrc "remaps/dry_bones_bony_beetle.asm"
incsrc "remaps/eerie.asm"
incsrc "remaps/falling_spike.asm"
incsrc "remaps/fish.asm"
incsrc "remaps/fishbone.asm"
incsrc "remaps/fishin_boo.asm"
incsrc "remaps/floating_spike_ball.asm"
incsrc "remaps/football.asm"
incsrc "remaps/fuzzy.asm"
incsrc "remaps/ghost_house_ledge_hole.asm"
incsrc "remaps/goal_sphere.asm"
incsrc "remaps/goomba.asm"
incsrc "remaps/grey_lava_plat.asm"
incsrc "remaps/grey_spin_plat.asm"
incsrc "remaps/grinders.asm"
incsrc "remaps/growing_pipe.asm"
incsrc "remaps/hammer_bro.asm"
incsrc "remaps/hoppin_flame.asm"
incsrc "remaps/hothead.asm"
incsrc "remaps/koopas.asm"
incsrc "remaps/lakitu.asm"
incsrc "remaps/mechakoopa.asm"
incsrc "remaps/magikoopa.asm"
incsrc "remaps/mega_mole.asm"
incsrc "remaps/messagebox.asm"
incsrc "remaps/monty_mole.asm"
incsrc "remaps/mush_scale_plat.asm"
incsrc "remaps/ninji.asm"
incsrc "remaps/para_bobomb_and_goomba.asm"
incsrc "remaps/pencil.asm"
incsrc "remaps/piranhas.asm"
incsrc "remaps/pballoon.asm"
incsrc "remaps/pokey.asm"
incsrc "remaps/porcu_puffer.asm"
incsrc "remaps/reflecting_fireball.asm"
incsrc "remaps/rock_grass_plat.asm"
incsrc "remaps/rope_machine.asm"
incsrc "remaps/rex.asm"
incsrc "remaps/rip_van_fish.asm"
incsrc "remaps/skull_plat.asm"
incsrc "remaps/spike_top.asm"
incsrc "remaps/spiny.asm"
incsrc "remaps/stinky_bubble.asm"
incsrc "remaps/sumobro.asm"                   ; includes sumo's lightning
incsrc "remaps/super_koopa.asm"               ; TODO not completed, buggy frames
incsrc "remaps/swooper.asm"
incsrc "remaps/thwimp.asm"
incsrc "remaps/thwomp.asm"
incsrc "remaps/timed_plat.asm"
incsrc "remaps/torpedo_ted.asm"               ; includes extended launcher arm
incsrc "remaps/urchin.asm"
incsrc "remaps/volcano_lotus.asm"
incsrc "remaps/wiggler.asm"                   ; includes extended flower
incsrc "remaps/wood_checker_plats.asm"
incsrc "remaps/wood_spinny_plat.asm"
incsrc "remaps/yoshi.asm"

; cluster sprite remaps
incsrc "remaps/cls_boos.asm"
incsrc "remaps/cls_castle_bg_flame.asm"
incsrc "remaps/cls_sumo_fire.asm"

; extended sprite remaps
incsrc "remaps/ext_baseball.asm"
incsrc "remaps/ext_bone.asm"
incsrc "remaps/ext_coingame_coin.asm"
incsrc "remaps/ext_hammer.asm"
incsrc "remaps/ext_lotus_pollen.asm"
incsrc "remaps/ext_yoshi_fireball.asm"

; minor extended sprite remaps
incsrc "remaps/mex_boostream.asm"

incsrc "remaps/bounce_sprites.asm"
